# permissions for end users to view tomcats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tomcat-viewer-role
rules:
- apiGroups:
  - apache.org
  resources:
  - tomcats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apache.org
  resources:
  - tomcats/status
  verbs:
  - get
