# permissions for end users to edit tomcats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tomcat-editor-role
rules:
- apiGroups:
  - apache.org
  resources:
  - tomcats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apache.org
  resources:
  - tomcats/status
  verbs:
  - get
