apiVersion: apache.org/v1alpha1
kind: Tomcat
metadata:
  name: tomcat-sample
spec:
  # Add fields here
  applicationName: tomcat
  replicas: 2
  tomcatImage:
    applicationImage: tomcat:latest
    tomcatWebApp:
      webArchiveImage: maven:3.8.1-openjdk-8
      webAppURL: https://github.com/jfclere/demo-webapp