apiVersion: apache.org/v1alpha1
kind: Tomcat
metadata:
  name: tomcat-sample
spec:
  # Add fields here
  applicationName: tomcat
  replicas: 2
  image:
    applicationImage: tomcat:latest
    webApp:
      # name: ROOT
      name: demo-1
      builderImage: maven:3.8.1-openjdk-8
      sourceRepositoryURL: https://github.com/jfclere/demo-webapp
      sourceRepositoryRef: "master"
      contextDir: .
      deployPath: /usr/local/tomcat/webapps/
      applicationSize: 1Gi
      buildScript : 'webAppWarFileName="demo-1.war";
        webAppSourceRepositoryURL="https://github.com/jfclere/demo-webapp";
        webAppSourceRepositoryRef="master";
        webAppSourceRepositoryContextDir=".";
        if [ -z ${webAppSourceRepositoryURL} ]; then
          echo "Need an URL like https://github.com/jfclere/demo-webapp.git";
          exit 1;
        fi;
        git clone ${webAppSourceRepositoryURL};
        if [ $? -ne 0 ]; then
          echo "Can not clone ${webAppSourceRepositoryURL}";
          exit 1;
        fi;
        DIR=$(echo ${webAppSourceRepositoryURL##*/});
        DIR=$(echo ${DIR%%.*});
        cd ${DIR};
        if [ ! -z ${webAppSourceRepositoryRef} ]; then
          git checkout ${webAppSourceRepositoryRef};
        fi;
        if [ ! -z ${webAppSourceRepositoryContextDir} ]; then
          cd ${webAppSourceRepositoryContextDir};
        fi;
        mvn clean install;
        if [ $? -ne 0 ]; then
          echo "mvn install failed please check the pom.xml in ${webAppSourceRepositoryURL}";
          exit 1;
        fi;
        cp target/*.war /mnt/${webAppWarFileName};'